spring:
  application:
    name: hello-server
  cloud:
    config:
      fail-fast: true

server:
  port: 8098

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true

ribbon:
  http:
    client:
      enabled: false