#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      serviceId: HELLO-SERVER
#      stripPrefix: false
#    hello-client:
#      path: /client/**
#      serviceId: HELLO-CLIENT
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true

server:
  port: 8079

spring:
  application:
    name: zuul-service