#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

#TODO Zuul routing works locally, but does not work in docker

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      serviceId: HELLO-SERVER
#      stripPrefix: false
    hello-consumer:
      path: /consumer/**
      serviceId: HELLO-CONSUMER
#      stripPrefix: false
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 8079

spring:
  application:
    name: zuul-service