spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        bootstrap: false
  profiles:
    active: native
    client:
      hostname: ${spring.application.name}

  application:
    name: config-server

server:
  port: 8060

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
