spring:
  application:
    name: hello-consumer
  cloud:
    client:
      hostname: ${spring.application.name}

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true