spring:
  application:
    name: hello-consumer

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true