spring:
  application:
    name: eureka-service
  cloud:
    client:
      hostname: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 8070

